version: '2.1'

services:
  demo:
    build: .
    ports:
      - 80:80
    depends_on:
      - redis
      - postgres
    environment:
      TEST_TOKEN: Testing123
  redis:
    image: redis:3.0.5
  postgres:
     image: postgres:9.3.6
